services:
  auth:
    build: ./services/auth
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth/.env
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    depends_on:
      - kafka

  utils:
    build: ./services/utils
    ports:
      - "5001:5001"
    env_file:
      - ./services/utils/.env
    volumes:
      - ./services/utils:/app
      - /app/node_modules
    depends_on:
      - kafka

  user:
    build: ./services/user
    ports:
      - "5002:5002"
    env_file:
      - ./services/user/.env
    volumes:
      - ./services/user:/app
      - /app/node_modules

  job:
    build: ./services/job
    ports:
      - "5003:5003"
    env_file:
      - ./services/job/.env
    volumes:
      - ./services/job:/app
      - /app/node_modules

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
